# Generated by Django 3.1.7 on 2021-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210405_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='color',
            field=models.CharField(choices=[('Blk', 'Black'), ('Wht', 'White'), ('Gry', 'Gray')], default='L', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
